/*
 * This source file was generated by the Gradle 'init' task
 */
package digitalclock;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
  @Test
  void appHasAGreeting() {
    // DigitalClock classUnderTest = new DigitalClock();
    assertTrue(true, "App should be instantiated.");
  }
}
